# 배포용
services:
  app:
    image: augustzer0/saksak:latest
    container_name: saksak-back
    restart: always
    ports:
      - "8000:8000"
    command: ["uv", "run", "fastapi", "run", "src/main.py", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - saksak-network
      - npm-network
    env_file:
      - .env
    environment:
      - DB_HOST=saksak-db
      - REDIS_URL=redis://saksak-redis:6379/0
      - TZ=Asia/Seoul

  postgresql:
    image: pgvector/pgvector:pg15
    container_name: saksak-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=saksak
      - TZ=Asia/Seoul
    ports:
      - "100.107.7.25:5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - saksak-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d saksak" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: saksak-redis
    networks:
      - saksak-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  saksak-network:
  npm-network:
    external: true

volumes:
  postgres_prod_data: